name: Run CAR-T Lymphoma Bibliometrics

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 2 * * 0"  # Sundays 02:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collector
        env:
          NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
        run: |
          python scripts/collect_cart.py
      - name: Verify CSV presence
        run: |
          echo "Listing data directory:"
          ls -lah data || true
          echo "Show first lines if file exists:"
          head -n 5 data/cart_lymphoma_2009_2025.csv || true
      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A data
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update CAR-T lymphoma dataset"
            git push
          fi
